# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'semi2_세번째 실습' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for semi2_세번째 실습

pod 'CHIPageControl', '~> 0.1.3'

end
